# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

include: package:lints/core.yaml

analyzer:
  exclude:
    - lib/src/*.g.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - prefer_single_quotes
    - unawaited_futures
