# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: croft
description: ChROmium Flatpak Toolkit

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  checked_yaml: ^2.0.1
  file: ^6.1.2
  json_annotation: ^4.7.0
  logging: ^1.0.1
  meta: ^1.7.0
  path: ^1.8.0
  plade:
    git:
      url: https://github.com/refi64/plade
      ref: 0254886e41c71108a9f7d8391a0483cf7a288682
  posix: ^4.0.0
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^6.4.0
  lints: ^1.0.1

# dependency_overrides:
#   plade:
#     path: ../plade
